proxy:
  title: Wiktionary Cognate Dashboard
  # logo-url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Wikidata-logo-en.svg/320px-Wikidata-logo-en.svg.png
  landing-page: /app_direct/Wiktionary_CognateDashboard
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  favicon-path: favicon.png
  hide-navbar: true
  # Docker configuration
  docker:
    # cert-path: /home/none
    # url: http://localhost:2375
    # port-range-start: 20000
    internal-networking: true
  specs:
  - id: Wiktionary_CognateDashboard
    display-name: Wiktionary Cognate Dashboard
    description: Wiktionary Cognate Dashboard
    container-image: wiktionarycognate-img
    container-network: wd-analytics-net
    container-volumes: [ "/home/goransm/_Img/_wiktionary_data:/app/_wiktionary_data:/build_zone/_wiktionary_data", "/home/goransm/_Img/_wiktionary_data/projectData:/build_zone/_wiktionary_data/projectData", "/home/goransm/_Img/_wiktionary_data/instructions:/build_zone/_wiktionary_data/instructions" ]
logging:
  file:
    shinyproxy.log
    
# Network:
# sudo docker network create wd-analytics-net
# Build: sudo docker build . -t wd-analytics-shinyproxy
# Run: sudo docker run -d -v /var/run/docker.sock:/var/run/docker.sock --net wd-analytics-net -p 80:8080 wd-analytics-shinyproxy

