version: "3.0"

services:
  wiktionarycognatedashboard:
    container_name: wiktionarycognate
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    image: wiktionarycognate-img
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
      - '80:3838'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - '/home/goransm/_Img/_wiktionary_data:/app/_wiktionary_data:/build_zone/_wiktionary_data'
      - '/home/goransm/_Img/_wiktionary_data/projectData:/build_zone/_wiktionary_data/projectData'
      - '/home/goransm/_Img/_wiktionary_data/instructions:/app/_wiktionary_data/instructions:/build_zone/_wiktionary_data/instructions'

volumes:
  shiny_logs: